CREATE TABLE documento (
  id INT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL,
  enlace VARCHAR(255) NOT NULL,
  categoria VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO documento (titulo, enlace, categoria) VALUES
('Sistema de bicicletas de pedaleo asistido en el tramo terminal - UPTC Sede Central', 'https://repositorio.uptc.edu.co/handle/001/8851', 'Transito'),
('Accesibilidad y movilidad incluyente - caso Tunja', 'https://repositorio.uptc.edu.co/handle/001/8845', 'Transito'),
('Apoyo a la planeación y evaluación de proyectos de accesibilidad y movilidad incluyente en la Alcaldía Mayor de Tunja', 'https://repositorio.uptc.edu.co/handle/001/8842', 'Transito'),
('Alternativas de cruce peatonal en la entrada principal de la UPTC mediante software de microsimulación', 'https://repositorio.uptc.edu.co/handle/001/8840', 'Transito'),
('Guía metodológica para la implementación de estrategias de movilidad segura en Tunja mediante urbanismo táctico', 'https://repositorio.uptc.edu.co/handle/001/8522', 'Transito'),
('Metodología para evaluar la accesibilidad de personas con movilidad reducida. Caso estudio : Centro Histórico, Tunja', 'https://repositorio.uptc.edu.co/handle/001/3784', 'Transito'),
('Análisis del comportamiento y heterogeneidad en las elecciones de los usuarios de bicitaxi en Bogotá', 'https://repositorio.uptc.edu.co/handle/001/3783', 'Transito'),
('Determinación del flujo de saturación base (So) para ciudades pequeñas, caso Tunja', 'https://repositorio.uptc.edu.co/handle/001/3781', 'Transito'),
('Acompañamiento técnico y logístico en realización de estudios de tránsito de proyectos urbanísticos en Bogotá', 'https://repositorio.uptc.edu.co/handle/001/3780', 'Transito'),
('Calibración y validación de parámetros de comportamiento mediante microsimulación en intersecciones, caso estudio Tunja', 'https://repositorio.uptc.edu.co/handle/001/3772', 'Transito'),
('Modelo de predicción de ruido producido por el tráfico vehicular urbano mediante redes neuronales artificiales', 'https://repositorio.uptc.edu.co/handle/001/3771', 'Transito'),
('Factores que determinan la acción de chatear por celular mientras se camina', 'https://repositorio.uptc.edu.co/handle/001/3102', 'Transito'),
('Estructuración de un mapa de riesgo de accidentes de tránsito en Tunja mediante SIG', 'https://repositorio.uptc.edu.co/handle/001/3091', 'Transito'),
('Seguridad vial en el corredor entre la UPTC y las Nieves', 'https://repositorio.uptc.edu.co/handle/001/3085', 'Transito'),
('Brechas críticas en cruces peatonales no controlados en vías arterias de Tunja', 'https://repositorio.uptc.edu.co/handle/001/3073', 'Transito'),
('Caracterización de la movilidad peatonal en los accesos y salidas de una Estación BRT, caso Transmilenio', 'https://repositorio.uptc.edu.co/handle/001/3071', 'Transito'),
('Auditoria de seguridad vial en el tramo comprendido entre Tunja y el municipio de Tuta', 'https://repositorio.uptc.edu.co/handle/001/3070', 'Transito'),
('Apoyo técnico en monitoreo de seguimiento y control del tránsito y transporte, Bogotá D.C.', 'https://repositorio.uptc.edu.co/handle/001/3069', 'Transito'),
('Plan de gestión para los principales sitios críticos de accidentalidad en la ciudad de Tunja (Etapa 1)', 'https://repositorio.uptc.edu.co/handle/001/3068', 'Transito'),
('Caracterización de las zonas de cargue y descargue de mercancías en la ciudad de Tunja.', 'https://repositorio.uptc.edu.co/handle/001/8852', 'Transporte'),
('Efectos de la pandemia del Covid-19 en la oferta y demanda de los sistemas BRT de Bogotá y Medellín', 'https://repositorio.uptc.edu.co/handle/001/8844', 'Transporte'),
('Caracterización preliminar de los efectos de la línea férrea en su zona aledaña- caso Tunja', 'https://repositorio.uptc.edu.co/handle/001/8841', 'Transporte'),
('Caracterización, inventario, diagnóstico y propuesta funcional proyecto “Vía transversal de Boyacá”, tramo: Miraflores-Monterrey', 'https://repositorio.uptc.edu.co/handle/001/8832', 'Transporte'),
('Conductores de transporte público colectivo urbano en Tunja. La percepción de su calidad de vida', 'https://repositorio.uptc.edu.co/handle/001/8526', 'Transporte'),
('La perspectiva de género en la planificación del transporte urbano. Revisión de aspectos metodológicos', 'https://repositorio.uptc.edu.co/handle/001/8524', 'Transporte'),
('Prefactibilidad técnica para implementar el servicio público de transporte terrestre automotor mixto en Jenesano – Boyacá', 'https://repositorio.uptc.edu.co/handle/001/3785', 'Transporte'),
('Calidad y nivel de servicio del transporte público colectivo urbano de la ciudad de Tunja', 'https://repositorio.uptc.edu.co/handle/001/3782', 'Transporte'),
('Ajuste al transporte público colectivo urbano de Tunja : integración con el terminal interurbano', 'https://repositorio.uptc.edu.co/handle/001/3779', 'Transporte'),
('Análisis de rutas internas y externas del acopio de carbón “El Triunfo” en Paipa Boyacá', 'https://repositorio.uptc.edu.co/handle/001/3776', 'Transporte'),
('Guía para el desarrollo orientado al transporte sostenible (DOTS) en ciudades intermedias', 'https://repositorio.uptc.edu.co/handle/001/3768', 'Transporte'),
('Estimación de la demanda con encuestas de preferencia declaradas para el tren de pasajeros Sogamoso Tunja', 'https://repositorio.uptc.edu.co/handle/001/3101', 'Transporte'),
('Movilidad interna peatonal en plataformas de estaciones; sistemas de transporte masivo BRT – caso Bogotá', 'https://repositorio.uptc.edu.co/handle/001/3084', 'Transporte'),
('Análisis de preferencias por modos alternativos de transporte para acceder al Campus de la UPTC', 'https://repositorio.uptc.edu.co/handle/001/3081', 'Transporte'),
("Estudio de preferencias de transporte para personas en situación de discapacidad en la ciudad de Tunja", "https://repositorio.uptc.edu.co/handle/001/3077", "Transporte"),
("Elaboración del plan estratégico de seguridad vial del proveedor de servicio de transporte de la Empresa Cargando S.A.", "https://repositorio.uptc.edu.co/handle/001/3074", "Transporte"),
("Determinación de la percepción del sistema de bicicletas públicas de la ciudad de Tunja", "https://repositorio.uptc.edu.co/handle/001/3050", "Transporte"),
('Participación en práctica empresarial en la entidad INVIAS apoyo técnico en contratos y convenios en la Dirección Territorial Meta', 'https://repositorio.uptc.edu.co/handle/001/8850', 'Infraestructura'),
('Control de calidad de obras viales utilizando la técnica estadística media móvil', 'https://repositorio.uptc.edu.co/handle/001/8849', 'Infraestructura'),
('Supervisión y apoyo técnico en la Oficina Asesora de Planeación del municipio de Sora-Boyacá', 'https://repositorio.uptc.edu.co/handle/001/8848', 'Infraestructura'),
('Apoyo en la Dirección Operativa de Control Fiscal de Obras Civiles de la Contraloría General de Boyacá', 'https://repositorio.uptc.edu.co/handle/001/8847', 'Infraestructura'),
('Gestión y apoyo del control fiscal en la Contraloría General del departamento de Boyacá', 'https://repositorio.uptc.edu.co/handle/001/8846', 'Infraestructura'),
('Apoyo a proyectos de red terciaria y férrea en territorial Huila de Instituto Nacional de Vías', 'https://repositorio.uptc.edu.co/handle/001/8843', 'Infraestructura'),
('Pasantía en la empresa ORBEING S.A.S. como auxiliar de ingeniería de obras viales', 'https://repositorio.uptc.edu.co/handle/001/8839', 'Infraestructura'),
('Apoyo a la supervisión de obras en la Secretaría de Infraestructura, Alcaldía de Tunja', 'https://repositorio.uptc.edu.co/handle/001/8838', 'Infraestructura'),
('Apoyo técnico administrativo en la interventoría a obras de drenaje vial del Contrato 3561-2014', 'https://repositorio.uptc.edu.co/handle/001/8837', 'Infraestructura'),
('Influencia del polvo de alto horno en el daño por humedad en concretos asfálticos', 'https://repositorio.uptc.edu.co/handle/001/8836', 'Infraestructura'),
('Apoyo técnico en la elaboración y revisión de diseños de pavimentos en el municipio de Motavita-Boyacá', 'https://repositorio.uptc.edu.co/handle/001/8835', 'Infraestructura'),
("Análisis técnico-económico y de interventoría de la implementación del pavimento tipo placa-huella en San José de Suaita (Santander)", "https://repositorio.uptc.edu.co/handle/001/8528", "Infraestructura"),
("Apoyo técnico en diferentes proyectos del área de infraestructura en el municipio de Tunja", "https://repositorio.uptc.edu.co/handle/001/8525", "Infraestructura"),
("Evaluación técnica - económica en obras de estabilización de taludes en la vía San Gil Charalá", "https://repositorio.uptc.edu.co/handle/001/8523", "Infraestructura"),
("Análisis de preferencias por tipo de infraestructura para bicicleta", "https://repositorio.uptc.edu.co/handle/001/3786", "Infraestructura"),
("Diseño geométrico calles 51, 52 y vía paralela al Ferrocarril Tunja", "https://repositorio.uptc.edu.co/handle/001/3778", "Infraestructura"),
("Evaluación del comportamiento del concreto hidráulico tras la inclusión de tubos al interior de Vigas", "https://repositorio.uptc.edu.co/handle/001/3777", "Infraestructura"),
("Representación georreferenciada de las rutas de prácticas académicas para programas de pregrado, UPTC – Tunja", "https://repositorio.uptc.edu.co/handle/001/3770", "Infraestructura"),
('Diseño geométrico Avenida del Río Tunja (entre calles 15 y 24)', 'https://repositorio.uptc.edu.co/handle/001/3769', 'Infraestructura'),
('Uso de polvillo de alto horno como material fino en Mezclas Densas en Caliente MDC-19', 'https://repositorio.uptc.edu.co/handle/001/3767', 'Infraestructura'),
('Análisis de datos en la auscultación de pavimentos empleando equipos de prueba no destructiva', 'https://repositorio.uptc.edu.co/handle/001/3766', 'Infraestructura'),
('Actualización de la caracterización en la red vial de la Provincia de Neira', 'https://repositorio.uptc.edu.co/handle/001/3114', 'Infraestructura'),
('Actualización cartográfica, catastral y vial del Sector 2 de Tunja, utilizando información georreferenciada', 'https://repositorio.uptc.edu.co/handle/001/3104', 'Infraestructura'),
('Actualización cartográfica, catastral y vial del Sector 8 de Tunja utilizando información georreferenciada', 'https://repositorio.uptc.edu.co/handle/001/3103', 'Infraestructura'),
('Supervisión a la construcción de placa huella y obras de drenaje vial, municipio de Togüí', 'https://repositorio.uptc.edu.co/handle/001/3100', 'Infraestructura'),
('Efecto del grano de caucho en el ahuellamiento de una mezcla asfáltica tipo MD-12', 'https://repositorio.uptc.edu.co/handle/001/3094', 'Infraestructura'),
('Inspección y análisis del estado de la señalización horizontal y vertical en el centro urbano del municipio de Paipa barrios Centro y Gaitán', 'https://repositorio.uptc.edu.co/handle/001/3093', 'Infraestructura'),
('Caracterización de la red vial de los municipios de Almeida, Chivor, Guayatá y Somondoco', 'https://repositorio.uptc.edu.co/handle/001/3092', 'Infraestructura'),
('Formulación de vía verde como alternativa de movilidad y recuperación ambiental del río Jordán Tunja', 'https://repositorio.uptc.edu.co/handle/001/3090', 'Infraestructura'),
('Diseño geométrico y estudios de las vías urbanas : Hayuelos, Toyota y Seminario de Tunja', 'https://repositorio.uptc.edu.co/handle/001/3089', 'Infraestructura'),
('Apoyo técnico a interventoría para mejoramiento y rehabilitación de la carretera Landázuri–Barbosa, departamento de Santander', 'https://repositorio.uptc.edu.co/handle/001/3086', 'Infraestructura'),
('Desempeño de un concreto hidráulico adicionado con vidrio molido reciclado y EAFS', 'https://repositorio.uptc.edu.co/handle/001/3083', 'Infraestructura'),
('Apoyo técnico en el diseño y construcción de puentes modulares vehiculares en acero', 'https://repositorio.uptc.edu.co/handle/001/3082', 'Infraestructura'),
('Diseño de la red de estacionamientos para bicicletas en la Universidad Pedagógica y Tecnológica de Colombia sede Tunja', 'https://repositorio.uptc.edu.co/handle/001/3080', 'Infraestructura'),
('Análisis del comportamiento de concreto hidráulico adicionado con EAFS y polvo de vidrio reciclado', 'https://repositorio.uptc.edu.co/handle/001/3079', 'Infraestructura'),
('Corrección topológica y priorización de vías de la Provincia Centro del departamento de Boyacá', 'https://repositorio.uptc.edu.co/handle/001/3076', 'Infraestructura'),
('Actualización y diagnóstico del inventario vial de la Provincia Norte - Departamento de Boyacá', 'https://repositorio.uptc.edu.co/handle/001/3075', 'Infraestructura'),
('Actualización de la red vial de los municipios de Guateque, La Capilla, Sutatenza y Tenza mediante SIG', 'https://repositorio.uptc.edu.co/handle/001/3072', 'Infraestructura');






